// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppBoot(arg1:string):Promise<Array<main.FileTree>>;

export function ClipboardGetText():Promise<string>;

export function CopyEntry(arg1:string,arg2:string):Promise<void>;

export function CreateIssue(arg1:string,arg2:string):Promise<main.Issue>;

export function DeleteEntry(arg1:string):Promise<void>;

export function DeleteIssue(arg1:string,arg2:number):Promise<void>;

export function ExistsJSON(arg1:string):Promise<boolean>;

export function GetConfig():Promise<main.UserConfig>;

export function GetWorkspacePath():Promise<string>;

export function InitJSON(arg1:string):Promise<void>;

export function ListIssues(arg1:string):Promise<Array<main.Issue>>;

export function MakeDir(arg1:string):Promise<void>;

export function MoveEntry(arg1:string,arg2:string):Promise<void>;

export function ReadIssue(arg1:string,arg2:number):Promise<main.Issue>;

export function ReadJSON(arg1:string):Promise<any>;

export function ReadText(arg1:string):Promise<string>;

export function RenameEntry(arg1:string,arg2:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetWorkspacePath(arg1:string):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function ToggleIssueSubissue(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<main.Issue>;

export function UpdateIssue(arg1:string,arg2:number,arg3:main.IssueUpdate):Promise<main.Issue>;

export function UpdateIssueLimitDate(arg1:string,arg2:number,arg3:any):Promise<main.Issue>;

export function UpdateIssueStatus(arg1:string,arg2:number,arg3:string):Promise<main.Issue>;

export function WriteJSON(arg1:string,arg2:any):Promise<void>;

export function WriteText(arg1:string,arg2:string):Promise<void>;
