// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppBoot(arg1) {
  return window['go']['main']['App']['AppBoot'](arg1);
}

export function ClipboardGetText() {
  return window['go']['main']['App']['ClipboardGetText']();
}

export function CopyEntry(arg1, arg2) {
  return window['go']['main']['App']['CopyEntry'](arg1, arg2);
}

export function CreateIssue(arg1, arg2) {
  return window['go']['main']['App']['CreateIssue'](arg1, arg2);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteIssue(arg1, arg2) {
  return window['go']['main']['App']['DeleteIssue'](arg1, arg2);
}

export function ExistsJSON(arg1) {
  return window['go']['main']['App']['ExistsJSON'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetWorkspacePath() {
  return window['go']['main']['App']['GetWorkspacePath']();
}

export function InitJSON(arg1) {
  return window['go']['main']['App']['InitJSON'](arg1);
}

export function ListIssues(arg1) {
  return window['go']['main']['App']['ListIssues'](arg1);
}

export function MakeDir(arg1) {
  return window['go']['main']['App']['MakeDir'](arg1);
}

export function MoveEntry(arg1, arg2) {
  return window['go']['main']['App']['MoveEntry'](arg1, arg2);
}

export function ReadIssue(arg1, arg2) {
  return window['go']['main']['App']['ReadIssue'](arg1, arg2);
}

export function ReadJSON(arg1) {
  return window['go']['main']['App']['ReadJSON'](arg1);
}

export function ReadText(arg1) {
  return window['go']['main']['App']['ReadText'](arg1);
}

export function RenameEntry(arg1, arg2) {
  return window['go']['main']['App']['RenameEntry'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetWorkspacePath(arg1) {
  return window['go']['main']['App']['SetWorkspacePath'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function ToggleIssueSubissue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ToggleIssueSubissue'](arg1, arg2, arg3, arg4);
}

export function UpdateIssue(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateIssue'](arg1, arg2, arg3);
}

export function UpdateIssueLimitDate(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateIssueLimitDate'](arg1, arg2, arg3);
}

export function UpdateIssueStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateIssueStatus'](arg1, arg2, arg3);
}

export function WriteJSON(arg1, arg2) {
  return window['go']['main']['App']['WriteJSON'](arg1, arg2);
}

export function WriteText(arg1, arg2) {
  return window['go']['main']['App']['WriteText'](arg1, arg2);
}
